# Generated by Django 4.0.3 on 2022-04-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes_post_user_userprofile_friendship_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
