# Generated by Django 4.0.4 on 2022-04-15 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 4, 39, 8, 175920, tzinfo=utc)),
        ),
    ]
