# Generated by Django 4.0.4 on 2022-04-16 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_timestamp_userprofile_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='I am an arbitrary user with zero personality...', max_length=400),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 5, 37, 41, 165095, tzinfo=utc)),
        ),
    ]
