# Generated by Django 4.0.4 on 2022-04-16 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_rename_friend_friendship_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='time_created',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 17, 47, 59, 475518, tzinfo=utc)),
        ),
    ]
