# Generated by Django 4.0.4 on 2022-04-16 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_friendship_time_created_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 17, 50, 43, 534046, tzinfo=utc)),
        ),
    ]
